-- ============================================================================
-- 0006_seed_archive_content.sql — Phase 1 content migration
--
-- Updates the placeholder shells (0004) with content extracted from the
-- Google Sites takeout. Embedded markdown bodies use dollar-quoted strings;
-- image URLs point at the ImageKit account.
--
-- Generated by tools/migrate-google-site/src/build-migration.ts
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Seasons
-- ----------------------------------------------------------------------------

update public.seasons set
    name = 'Season I (2021)',
    year = 2021,
    display_order = 1,
    description_md = $md$We played the first season of crusade campaigns in early 2021. No public writeup made it onto the old Google Sites — _"we just played games!"_ as the source page put it.$md$
where slug = 'season-1';

update public.seasons set
    name = 'Season II (2021)',
    year = 2021,
    display_order = 2,
    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-1.jpg',
    description_md = $md$# Season 3 Campaign 

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-1.jpg)

# Season 2 Phase Three

Twenty games and two phases of the campaign down! The [Phase Two](/archive/recaps/s2-phase-two) page has been finalized with 8 games played over two game days.  The story for phase two was absolutely dominant play by the Raiders faction who went undefeated - in [Phase Three](/archive/recaps/s2-phase-three) it looks to be a close match with Attackers at 29 and Raiders at 20.  Although the Defenders only have 7, three big wins could put them back in contention.

Strategic Value Campaign:

Attackers: 1

Raiders: 2

Defenders: 0

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-2.jpg)

## [Phase One Analysis](/archive/recaps/s2-phase-one-analysis)

An overview of trends, changes and other key discussion from phase one of the campaign.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-3.jpg)

## [Narrative Battle Report](/archive/recaps/s2-battle-report-reclaiming-book-of-st-lucius)

Check out a narrative battle report of Carson's Sisters of Argent Shroud against Paul's Plague Marines.

Games will be Narrative Play (Crusade) using Power Level instead of points.  The goal of the campaign is to have your faction obtain the highest [Strategic Value](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Winning-the-Campaign).  To determine the winner of each campaign phase war zone points will be awarded - scoring will be dictated based on game size and winner via [War Zone points](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#War-Zone-Points) from War Zone: Charadon Act I: The Book of Rust.  You can view the war zone scoring via [Wahapedia](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#War-Zone-Points).  In addition to war zone points for battle size; during each phase of the campaign all players will generate a [Secret Order](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Secret-Orders) by rolling a D6 and submit a prediction via Warseers and Portents.  Once per campaign phase players may play that phases legendary mission for an additional War Zone point (phase one - [Rout on Okharium](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Rout-on-Okharium); phase two - [Flood Tide on Fathom](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Flood-Tide-on-Fathom); phase three - [Desperation and Despair](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Desperation-and-Despair)).

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-4.jpg)

## [Phase One](/archive/recaps/s2-phase-one)

September 1st thru October 6th

[Irradiated Wasteland](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Irradiated-Wasteland) rules will be in effect.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-5.jpg)

## [Phase Two](/archive/recaps/s2-phase-two)

October 7th thru November 17th

[Metalican Redoubt](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Metalican-Redoubt) rules will be in effect.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-6.jpg)

## [Phase Three](/archive/recaps/s2-phase-three)

November 18th thru December 31st

[Ascendancy of Entropy](https://wahapedia.ru/wh40k9ed/the-rules/charadon/#Ascendancy-of-Entropy) rules will be in effect.

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-7.jpg)

](S2%20-%20Player%20Hub%20Greensboro.html)

### Hub - Greensboro

Encompassing all players in Clemmons, Winston Salem, Greensboro, Raleigh and the surrounding areas.

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-8.jpg)

](S2%20-%20Player%20Hub%20Charlotte.html)

### Hub - Charlotte

Consists of the Charlotte Metro area and surrounding suburbs.

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-9.jpg)

](S2%20-%20Player%20Faction%20Defender.html)

## Defenders

Recommended faction for all Imperial Factions

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-10.jpg)

](S2%20-%20Player%20Faction%20Attacker.html)

## Attackers

Recommended faction for all Chaos Armies (or those dastardly Imperials who have recently fallen to Chaos)

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-11.jpg)

](S2%20-%20Player%20Faction%20Raider.html)

## Raiders

Recommended faction for all other Armies

# House Rules

[House Rules](/archive/pages/s2-house-rules) - to more adequately balance games and keep games moving quickly the linked house rules will apply to all games.

[Campaign Master Edicts](/archive/recaps/s2-campaign-master-edicts) - to ensure that a faction does not have a run away lead the linked Campaign Master Edicts will be live during this campaign.

FAQ - answers to some frequently asked questions.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-12.jpg)

[

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-13.jpg)

](https://forms.gle/5qe91mUCiKPoy3Ub6)

# Interested in Signing Up?

Please [submit](https://forms.gle/TWhfo4Nzi1PGUwoQ8) your Name, Phone Number, Email, Hub Location, and Army in the linked form.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-14.jpg)

[Submit your secret order](https://forms.gle/V3Jbho3YwTg7TKwy9)!

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-15.jpg)

[Submit a battle result](https://forms.gle/313WzC1EFaAd877WA)!

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-16.jpg)

[Submit your Warseers and Portents prediction](https://forms.gle/Npwig6qLFj96xsa27)!

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-2/image-17.jpg)

Need a Crusade Roster Format?  [Check out this one](https://docs.google.com/spreadsheets/d/10S23JPtOah6DB6xG61JHj7gMAxkgByxmuAd8nszNMpc/edit?usp=sharing)!

  2024.$md$
where slug = 'season-2';

update public.seasons set
    name = 'Season III (2022)',
    year = 2022,
    display_order = 3,
    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/seasons/season-3/image-1.jpg',
    description_md = $md$# Season 3 Campaign 

Current Leaderboard (shown below) | [Submit Turn Orders](https://forms.gle/p9FHiyRykB8C585w9) | [Submit Battle Results](https://forms.gle/pvQQyPfveeMFZZoe6) | [Special Rules Submission](https://forms.gle/FwiFaYCJ3Ff37zui8) | [Season 3 Data](https://docs.google.com/spreadsheets/d/10rlSgiBbioQZh4kH0E4v_zdqZvXq6nYBwvn1GSY-p8U/edit?usp=sharing)

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-3/image-1.jpg)

## Turn Five Results!

-   Hive Fleet Blue Crush (JN) attacks Vior'la Tau (PS) @ Fe'saan - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f) - Vior'la Tau (PS) defends!
    
-   Hive Fleet Kerberos (PM) attacks Il-Kaithe (CR) @ Jollov - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f) - Il-Kaithe (CR) defends!
    
-   WAAAGH! (GRIZZ) colonizes @ Wrath's Spire - [Colonization Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1gr39m58z73) - WAAAGH! (GRIZZ) succeeds!
    

## Queued Games!

There is one game left from turn three it needs to be played ASAP.

-   WAAGH! (CJ) attacks The Plexian Nest (Neutral) - [Colonization Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1gr39m58z73)
    

  

There are two games left from turn four, they should be played ASAP.

-   Hive Fleet Blue Crush (JN) attacks Deathwatch (BF) @ Castilos Nullifact - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f)
    
-   Imperial Knights (MH) attacks Vior'la Tau (PS) @ Fe'saan - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f)
    

  

There was one game in turn four unable to be played due to prior games being unresolved and some problems with scheduling.

-   Hive Fleet Kerberos (PM) attacks Coven of Shattered Visage (WB) @ Pax Argentius
    
    -   These two players should receive an intensive training action for that turn instead.
        

  

There are two games left from turn five, they should be played ASAP.

-   Il-Kaithe (CR) attacks Deathwatch (BF) @ Honourum - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f)
    
-   WAAGH! (CJ) attacks Hive Fleet Kerberos (PM) @ Misery - [Attack Scenarios](https://www.carolinafirstandonly.com/campaign-turns#h.s1ly5df6nx0f)
    

## Introduction

Welcome to Carolina's First and Only Season Three Campaign!  Similar to past campaigns - games will be Narrative Play (Crusade) using Power Level instead of points.  This season's campaign will run from April 18th, 2022 to December 12th, 2022 and by popular demand will be a map campaign.  

The goal of this year's campaign is to dominate the galaxy by holding systems and, depending on your faction, controlling specific systems on the map.  A full list of win conditions can be found on the Victory Conditions page.

To get started in the campaign use the [Crusade rules sections](https://wahapedia.ru/wh40k9ed/the-rules/narrative-play/) to build out your Order of  Battle with two key changes:

1.  Players Order of Battle Power Rating (or Supply Limit) starts at 100 Power Level rather than 50 Power Level.
    
2.  The Increase Supply Limit Requisition increases your Supply Limit by 10 Power instead of the original 5 Power.
    

Developer's Note: These two changes are in response to lessons learned from our last campaign.  The original Increase Supply Limit Requisition and 50 Power Level starting Order of Battle size were simply too small for players to even play 100 Power Level games by the end of the campaign and players even played 6-10 games.  This should also open up the possibility for players to play multiple sub-factions or at least be able to tailor options to opponents if they are not having success.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-3/image-2.jpg)

Artwork by [Thomas Elliott](https://art-of-thomas-elliott.tumblr.com/)

# Quick Overview

Players will generally start off the campaign by creating an Order of Battle - at a minimum this Order of Battle should contain 25 Power Level worth of units and enough units to play a "Combat Patrol" (that means at least a Patrol detachment or Super Heavy detachment if playing Knights).  A good format to use to track your Order of Battle include any of the google sheets at [tcrepo](https://docs.google.com/spreadsheets/d/10S23JPtOah6DB6xG61JHj7gMAxkgByxmuAd8nszNMpc/edit#gid=0), [reddit](https://docs.google.com/spreadsheets/d/1hqP9-R3rqHTFYUmUFhqt9KVC9USY4MSs-OdGsvJHMNg/edit?usp=sharing), or [battle bunker](https://docs.google.com/spreadsheets/d/1-fq0uo_j2muCZYBRaRMIXnCGr03Fb5Utc8ey7nCD64k/edit?usp=sharing).  Feel free to reach out to [our discord](https://discord.gg/WqQs328c9M) if you need help.  

You may go over 25 Power Level (it is recommended to go to 50 Power Level initially) and may even fill your entire 100 Power Level roster at the beginning of your campaign.  Of course you can purchase Increase Supply Limit Requisition requisitions to increase your Order of Battle's roster even further.

Although you are not required to play games with painted miniatures - units that are fully painted will gain experience faster (per the House Rules) and playing games is always a great motivator to make progress in both building and painting.  After your army is ready, once the campaign starts each two week period will generally follow the below format:

1.  Players will have three days to submit their orders.  
    
2.  Campaign games will then be assigned over the next two days.  The map will be updated to show current actions.
    
3.  Over the next week and a half players will need to schedule and play their games with their opponent.  Players will log their results in a [google form](https://forms.gle/pvQQyPfveeMFZZoe6).
    
4.  At the end of the two week period we will update the map with systems changing hands and determine if there is a victor - if not we will proceed to the next turn.
    

A more detailed view of the campaign turns can be seen on the Campaign Turns page.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-3/image-3.jpg)

# Campaign Turns and Map

The campaign will be played in two week turns.  Each turn will have four phases with players giving a strategic order and then having a little less than two weeks to schedule and play their games.  The four phases of a turn are: Strategy, Scenario, Battle, and Resolution.  A full description of the campaign turn is available on the Campaign Turns page.  To see the current status of the campaign map please see the Campaign Map page.  To submit your turn orders please use the [google form](https://forms.gle/p9FHiyRykB8C585w9).

# House Rules

House Rules - to more adequately balance games and keep games moving quickly the linked house rules will apply to all games.

Victory Conditions - want to see the current victory conditions and campaign map?  This is where you find it.

FAQ - answers to some frequently asked questions.

[Submit Turn Orders](https://forms.gle/p9FHiyRykB8C585w9) - Once every two weeks makes sure you submit your turn orders.

[Submit Battle Results](https://forms.gle/pvQQyPfveeMFZZoe6) - Send them in through the google form.

[Special Rules Submission](https://forms.gle/FwiFaYCJ3Ff37zui8) - Need to absorb biomass?  Take over a system with diplomacy or foretell to the doom of the galaxy?  Use the linked form.

![](https://ik.imagekit.io/carolinafirstandonly/seasons/season-3/image-4.jpg)

  2024.$md$
where slug = 'season-3';

-- ----------------------------------------------------------------------------
-- Special events (rename special-event-N → real slugs)
-- ----------------------------------------------------------------------------

update public.archive_events set
    slug = 'showdown-at-snyders',
    name = 'Showdown at Snyder''s',
    event_date = '2023-12-01',
    display_order = 1,
    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-one-knight-shelling.jpg',
    description_md = $md$# Showdown at Snyder's

Talk about a bad ass event! Hosted by the one and only Kris Snyder — this was a blast — we had a very fun group of people come out to the event:

**Host / Organizer / Adjudicator** — Kris Snyder

### Team Imperium

- Carson Street (Knights)
- Matt "Grizz" Myers (Salamanders)
- Chris Rice (Eldar)

### Team Chaos

- Bill Foster (Death Guard)
- Mike Holstein (Traitor Guard)
- Paul Street (Daemons)

Essentially the format of this event was three rounds of games:

1. Round one consisted of players pairing off and playing 1v1 in a custom narrative scenario.
2. Round two swapped those players around and had them play another 1v1 in another custom scenario.
3. Round three was a mass 3v3 game in a single scenario — the side that won the last game would win the gameday!

Games were played in early December (2023) at Kris's place.

## Preparation

Gamesday and other events are a great reason to get models painted — for this event I thought I needed to get some daemons ready. I had these models for a while and this was the perfect reason to get these models painted up. The biggest models I painted were Be'lakor and a Slaanesh Daemon Prince. Here are a few pictures:

## Round One

Round one consisted of three scenarios:

1. **Trench Line** — Where my Daemons played against Carson's Knights.
2. **Rail Yard** — Where Mike's Traitor Guard faced Chris's Eldar.
3. **Ruins** — Bill's Death Guard assailed Planetary Defense Forces defended by Grizz's Salamanders.

A review of every scenario is shown below — Kris set them up ahead of time and made gray scale photos of the terrain as prep for players. Talk about a cool setup. You can browse the scenarios below. Games were played at 500 points for the 1st round, 1k for second, and 1k for each army (3k per side) for the final round.

[Showdown at Snyder's — Scenario Presentation](https://docs.google.com/presentation/d/1RxvXdmWKizaKodygzID24KzLqrSfvHW5MjtAeksmpLg/present)

**My game:** For my first game I got paired against my wife, Carson, and talk about getting my shit kicked in. Whew — 500 pts of Daemons vs Knights did not go well. From memory I fielded a unit of Plaguebearers, Nurglings, Bloodletters, and a Slaanesh Daemon Prince. I believe I played against a single Knight and did maybe 7 wounds to it. Otherwise it was a pretty big blowout. The amazing thing about this scenario is that it let you use the earth shaker cannons to shoot other tables. As we were playing we mostly supported the game with Grizz against Bill (to little effect).

**Other games:** On the other tables Mike (Traitor Guard) had some horrendous dice rolling and lost to Chris's Eldar, while Bill (Death Guard) managed to kill all PDF forces in his game against Grizz (Salamanders). This put the Chaos forces down 1 game to 2 — however both games that Chaos lost did not affect the final battle; the game we won did. So all in all we thought we (Chaos) had a pretty good chance here.

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-one-knight-shelling.jpg"
    alt="Carson's Knight lobbing shells at other tables while Chris (Eldar) and Mike (Traitor Guard) fight over the train yard."
  />
  <figcaption>This is a great shot as you can see Carson's Knight lobbing shells at other tables while Chris (Eldar) and Mike (Traitor Guard) fight right over the train yard. We imagined that her knight was kicking or picking up and throwing the shells rather than operating the gun.</figcaption>
</figure>

## Round Two

Ok, round two is certainly where we probably lost overall gameday — while Bill would continue to carry us (Chaos), it was a complete disaster for myself and Mike only had a draw against Grizz. Games were 1k points in size and featured:

1. **My Daemons against Chris Rice and his Eldar** — talk about a freaking catastrophe — this game did not go well. While Be'lakor and the Daemon Prince would acquit themselves well, the Eldar units massacred my infantry units. The end result was a tragic Eldar victory where they would command an additional two tanks and a Baneblade in the final battle! We played the mission Tank Factory but I just did not have enough tough units to withstand any shooting from the Eldar and lost many of the objectives. Lacking enough maneuver elements to get those objectives back really hampered my chances of making this more competitive.
2. **Bill (Death Guard) vs my wife (Knights)** for the airfield on a second table — Bill managed to come away with his second win of the day. Carson really enjoyed this game and said Bill is the best of my friend group for her to play against. Bill would try his best to carry us (Mike and I) through the campaign with this second victory.
3. **Mike (Traitor Guard) vs Grizz (Salamanders)** would fight to a draw in their game (over the cathedral) — being a little behind the other tables in game resolution; however, their game had a negligible impact on the final game.

Images below show how my game went — Be'lakor almost made it through the Dire Avengers and Striking Scorpions but eventually fell to the mass attacks, mostly because he took six wounds from an Eldar-driven Leman Russ earlier in the game!

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-two-belakor-1.jpg"
    alt="Be'lakor advances into the Eldar lines."
  />
  <figcaption>Be'lakor advances into the Eldar lines.</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-two-belakor-2.jpg"
    alt="Be'lakor in the thick of the Dire Avengers and Striking Scorpions."
  />
  <figcaption>Be'lakor in the thick of the Dire Avengers and Striking Scorpions.</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-two-belakor-3.jpg"
    alt="Be'lakor falls to massed Eldar attacks after taking six wounds from a Leman Russ."
  />
  <figcaption>Be'lakor falls to massed Eldar attacks after taking six wounds from a Leman Russ.</figcaption>
</figure>

## The Final Round

So the final round battle was a wild time — with so many advantages for the Imperial side, we needed a lot of luck to pull out a victory. Unluckily for us that did not happen — although Bill would try to drag us across the finish line to victory (destroying multiple units including the Baneblade with his Knights), in the end the Chaos forces lacked enough melee threat to take the Cathedral from the Imperials. Unable to commit Be'lakor to the front and instead having to use him to hold the opposite side of the table objectives resulted in not enough forces concentrated on the cathedral half of the board.

Overall it was a great game day but ended up in an Imperial victory. Congrats to Carson, Grizz, and Chris Rice, and thanks to Kris Snyder for hosting and setting everything up.

Enjoy some pictures and captions of the game below.

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/final-factory-capture.jpg"
    alt="Chris's Eldar capture the factory and two tanks; Mike deploys his Traitor Guard, Poxwalkers, and Bill's Chaos Knights in the lower right."
  />
  <figcaption>Here you can see the disastrous consequences of my game with Chris — his capture of the factory and two tanks resulted in a significant bonus to his side compared to ours. In the lower right you can see Mike placing out his Traitor Guard; the Poxwalkers that Bill won from game one and Bill's Chaos Knights (he switched from Death Guard to Knights for the final game).</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/final-imperial-deploy.jpg"
    alt="The Imperial players deploy in cover."
  />
  <figcaption>The Imperial players desperately deploy in cover to avoid a possible Chaos first turn of shooting.</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/final-vindicare.jpg"
    alt="A Vindicare Assassin surveys the battlefield."
  />
  <figcaption>A Vindicare Assassin surveys the battlefield for his next target.</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/final-baneblade-down.jpg"
    alt="The Baneblade has been eliminated but Chaos infantry are missing from the middle of the board."
  />
  <figcaption>Although we (Chaos) managed to eliminate the Baneblade we made little headway across the board — here you can see most of the enemy army intact but almost no infantry of ours in the center of the field or even on their side of the board.</figcaption>
</figure>

<figure>
  <img
    src="https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/final-grizz-terminators.jpg"
    alt="Grizz's Terminators stand triumphant inside the unbreached chapel."
  />
  <figcaption>Grizz's Terminators stand triumphant inside the unbreached chapel to end the game day.</figcaption>
</figure>
$md$
where slug = 'special-event-1';

update public.archive_events set
    slug = 'old-alliances',
    name = 'Old Alliances',
    event_date = '2024-07-27',
    display_order = 2,
    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/events/old-alliances/image-1.jpg',
    description_md = $md$# Old Alliances

![](https://ik.imagekit.io/carolinafirstandonly/events/old-alliances/image-1.jpg)

# Old Alliances - July 27, 2024

An Alliance once existed between Clemmons and Winston-Salem. Long ago we painted armies and rolled dice together. We come to honor that allegiance. 

Calvinius at the Battle of Capernaum

## Overview

Old friends and allies – Drew Moxon will be in town on July 27, 2024!  As an homage to yesteryear a few of us are planning to meet up and hang out and play some Warhammer at my parent’s place (8914 Center Grove Church Road, Clemmons, NC) from 12pm-6pm.

## What to bring

Please bring either a snack food, drinks (both alcoholic and non-alcoholic are fine), and if you want to roll dice you may wish to bring your lucky dice.

## Activities

-   Warhammer Old World – Tears of Isha Campaign – Chris Rice and I will bring armies for the classic Empire vs High Elves matchup (only classic because that’s what both he and Drew fielded High Elves and I played Empire, lol).  We are adapting the 5th edition Tears of Isha Campaign to be played in the current edition.  Interested players will be divided up into teams with the goal of playing 2 scenario games over the afternoon (no need to bring minis or make lists – we should have everything ready).  If we have time we can re-rack scenarios if they are lopsided (or even swap sides).  This is a great way to learn the rules or see the game in action if you don’t want to role dice as a haughty High Elf or filthy human.
    
-   Build Stations – Need to build some minis?  We will have a couple of build stations available if you want to build/assemble some minis.  Make sure to bring your models, clippers, and glue (I should have a couple of cutting mats).
    
-   Eight Bit Nintendo in High Def – I will bring the Nintendo AVS along with a couple of controllers and games if people want to relive the glory that was 80s/90s San Francisco 49ers football, play some Tecmo Super Bowl scrimmages, or otherwise throw down some old games.
    
-   Catching Up – We're old now - take some time to catch up and check up on your buds.
    

## Invite List

·        Paul Street

·        Chris Rice

·        Drew Moxon

·        William Baucom

·        Brian Foster

·        Andrew Denson

·        Alex Taylor

### Invited but unable to attend

·        Colby Joyner

## Frequently Asked Questions

-   Can I bring my spouse/significant other?  Sure!  
    
-   Mind if I bring my kid(s)?  Go for it. My family does have a bunch of birds/chickens/peacocks if you want to take them for walk around the property and look at things.
    
-   What if I can only drop by? By all means if you want to just drop by for a few minutes and catch up feel free to do so.
    
-   Oh man, I still hang out with so and so from the Hanes middle school days, who we used to play Warhammer with, can I invite them?  Probably – tell me how many and who is coming so I can plan beforehand but it should not be a problem (these names come to mind although it has been years since I talked to them: Jon C, Dylan G, Justin Paul, etc.)
    
-   Parking?  Recommend you park on the paved driveway side of the house, in one of these areas.  It will be on the far side of the house from the direction you will be approaching.
    

![](https://ik.imagekit.io/carolinafirstandonly/events/old-alliances/image-2.jpg)

  2024.$md$
where slug = 'special-event-2';

update public.archive_events set
    slug = 'drafted',
    name = 'Drafted!',
    event_date = '2026-01-01',
    display_order = 3,
    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/events/drafted/image-1.jpg',
    description_md = $md$# Drafted!

![](https://ik.imagekit.io/carolinafirstandonly/events/drafted/image-1.jpg)

# Drafted! - Q1/Q2 2026

“The greatest victory of Chaos is not won by armies, but by the moment a good man decides his burden is someone else’s.”

— Saying of the Knights Templars

## Overview

The adventurers first uncovered hints of something foul in Bögenhafen almost by accident. What began as a simple errand through the dock district turned strange when they found odd ledgers, shipments marked with unfamiliar sigils, and scraps of parchment etched with the eight-pointed star hidden in a merchant’s warehouse. A cellar beneath the building held darker proof: scorched ritual circles, guttered black candles, and the lingering stink of warp-tainted incense. Whatever had happened there had been recent—and whatever the cult planned next was likely worse. The party exchanged uneasy looks, weighed the danger, and decided that discretion was the better part of survival. Before dawn they quietly rode out of town, telling themselves that the authorities—or someone more suitably heroic—would deal with it.

Months later that decision tasted like ashes. Their coin vanished in bad ale, worse gambling, and the endless road, until the last of their silver was gone. When recruiters of the provincial levy came through, promising meals and forgiveness of certain “misunderstandings,” the adventurers found themselves wearing the colors of the local army marching under grim banners. Now the road bends back toward Bogenhafen once more—but this time at the head of a column of nervous soldiers sent to reclaim a town overrun by cultists and daemons. As the walls appear on the horizon, the party recognizes the smoke rising above the rooftops and the distant echo of unholy bells… and realizes the horror awaiting them is the very one they chose not to stop.

## The enemy

The scout’s report was delivered breathless, boots still muddy, cloak half-torn by thorns from the forest's edge. He refused ale until he had spoken. When he did, his voice shook despite his effort to steady it.

“I swear by Sigmar, I ain’t seen the like of it before… and I pray I never do again.

It started with the sky.

Not clouds, mind you—colors. Wrong ones. Purples and blues swirling like oil on water. Then something moved inside it… wings the size of a windmill’s sails. A great bird-thing, but no bird Emperor ever made. Feathers of flame, eyes like burning lanterns. It floated above the rest like it owned the very air.

And gods help me, I think it did.

That creature was the master of them all—casting fire from its claws, laughing like a mad scholar. Blue flames rained down around it that burned the ground but not the things marching beneath.

Beneath that horror came the chattering mob.

Little things at first glance… pink as raw meat and giggling like children who know a cruel joke. But there were dozens of them. Two mobs at least—one small pack, maybe ten or so… and another nearly twice that size. They capered and shrieked in a tongue I couldn’t bear listening to long.

And among them marched the worst of that lot—tall, twisted things with long arms like burning branches. They spat gouts of warp-fire. Five of them I counted clearly, though the smoke made it hard to be certain. Wherever they pointed their hands the earth blackened.

That was only the first host.

Behind them strode something far worse.

A towering daemon, tall as an ogre but leaner, crowned with horns and wrapped in shadow like a cloak. It walked like a king surveying his lands. The others kept their distance from it. I think it was their lord… or maybe their executioner.

Around that monster ran hunting beasts—five red hounds with brass collars and jaws that never stopped snapping. They didn’t bark. They howled, like war horns made of meat.

Trailing behind them slithered three… things. I barely have words for them. Great piles of rot and tentacles, dragging themselves through the mud and leaving slime behind. The air around them smelled like a battlefield three days after the crows leave.

And dancing among that filth were six pale creatures shaped like women—but wrong. Too graceful. Too sharp. They moved like blades through water, laughing softly as they went.

I thought that was the whole host.

I was wrong.

From the tree line came the braying.

Beastmen. A small warband, but brutal looking. One big brute with twisted horns led them—carrying himself like a chieftain. Around ten of the goat-things marched behind him, banging crude weapons on shields like they were eager for blood.

And with them… the monsters.

Three Minotaurs.

Huge even by their kind. Muscles like siege engines and horns wide enough to gore a horse clean through. They walked at the rear like living battering rams.

“So that’s what’s coming for us,” the scout finished quietly.

“One sky-daemon leading a swarm of those pink horrors and fire-spitters… a horned prince commanding blood-hounds, rot-beasts, and those clawed temptress things… and a beastman warband with minotaurs bringing up the rear.”

He swallowed hard.

“I don’t know what foul alliance binds them… but I counted near sixty creatures of Chaos if I counted true.”

The man looked around the room at the gathered soldiers.

“And they’re marching this way.” ⚔️🔥

## The Empire Army

The sergeant dragged a whetstone down his halberd and gave the new recruits a long, unimpressed look.

“Welcome to the army of The Empire, whelps. Since you’re likely to die beside these fine folk, you may as well know their names.”

He jerked his chin toward the hill where the command banners snapped in the wind.

“That’s General Aldric von Krieger, riding his griffon Stormtalon. Veteran of three campaigns and owner of the daemon-killing blade Griefcleaver. Try not to embarrass him. Beside him rides the banner of Sir Otto Falkenhayn, bearer of the Valorous Standard of Altdorf. When that banner’s standing, men fight. When it falls… well, they usually don’t.”

He pointed toward the block of infantry drilling in the mud.

“That wall of iron is Captain Marta Riedel’s 1st Halberdiers – the Sockeyes. Thirty stubborn Reiklanders with halberds longer than their tempers. They hold the line while the rest of us pray the cannons do their job.”

The sergeant gestured toward the artillery park behind them.

“Guns belong to Master Gunner Holtz Brunner. Those two cannons are Iron Saint and Black Comet—fine pieces that can punch through a troll, a beastman, or a church wall if needed. That ugly contraption beside them is the Helblaster Sigmar’s Thunder. Fires so fast it turns a charge into soup. And that crew tamping powder is Old Kappel’s Bombard, our mortar—best used against enemies far away… preferably very far away.”

He nodded toward the treeline where bowstrings creaked.

“Scouts are the Grunburg Marksmen and the Altdorf Foresters—two bands of Reikland archers who know their way through woods and river fog better than most soldiers know their own boots.”

Down the road a patrol of cavalry wheeled their horses.

“That lot is Lieutenant Kaspar Dieter’s Outriders. Repeater guns, fast horses, and just enough discipline to stay out of the cannons’ way.”

His tone shifted slightly as a group of heavily armored knights assembled near the banner.

“And those shining statues there are Baron Lukas von Reik’s Reiksguard, the knights of The Silver Mantle. When they charge, the ground shakes and the enemy remembers somewhere else they’d rather be.”

Finally the sergeant pointed skyward, where wings cut through the clouds.

“And circling above is Magister Adelhard Zweig, master wizard of the Colleges, riding his pegasus Auriel. Carries scrolls to break enemy spells and a wand called Jetfire that can burn a monster to cinders.”

He planted the butt of his halberd in the mud and gave the recruits a crooked grin.

“So there you have it—generals, guns, knights, and a wizard who might accidentally incinerate you.”

He nodded toward the road ahead.

“Congratulations. You’re now part of the army marching on Bogenhafen… and rumor says the cultists own the place.”

  

## Frequently Asked Questions

-   What edition will the game be played?  5th!  Guess range weapons and magic cards in all their glory!
    

  

## Your Options:

  2024.$md$
where slug = 'special-event-3';

-- ----------------------------------------------------------------------------
-- Recaps (all attached to season-2)
-- ----------------------------------------------------------------------------

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-battle-report-flood-tide-on-fathom', s.id, 'Flood Tide on Fathom', $md$# Flood Tide on Fathom

This narrative battle report contains pictures and narrative summary of the events of a game played between Chris Rice's Eldar and Mike's Death Guard on October 9th.  Written by Chris Rice.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-flood-tide-on-fathom/image-1.jpg)

The discovery of the Death Guard’s plague tanks represented an urgent strategic threat. They were accumulating a contagion to unleash on the human forces, designed to render the vast numbers of dead more susceptible to becoming corpse puppets of chaos. The suffering decay of those who survived would feed the power of the Death Guard as well. This threatened to break what paltry useful resistance the imperials were providing. Due to the urgency of this mission, the Bloodcrafters strike force met with additional elements of the Glasper squadron and new aspect warrior reinforcements to aid in the assault.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-flood-tide-on-fathom/image-2.jpg)

The Aeldari forces quickly gained control of the facilities and set to draining the vile poxwaters that were amassing in the storage vats. Karash led the aspect warriors initial maneuver to quickly to outflank the ponderous chaos host. Poxridden corpses and cultists alike fell in a wind of shurikens, half of them rising again only to be cut down a second time. But these were mere pawns; their masters remained hidden from sight. As the autarch soared onward, his search found the sorcerer hidden amidst their ranks. A single shot from his expertly crafted pistol ripped the plaguecaster’s bloated body apart into a flaming husk.

As the psychic resistance of the vile sorcerer faded from Prydain’s mind, the farseer’s vision reached forward to reveal the enemy’s true plans. Their leader and his personal retinue standing ready in the teleportarium stepped through the warp and to the heart of the battle. With Aeldari speed these moments of foresight were more than enough to greet these warriors with a storm of blades and heat. Despite their bulwark of armor and their unfeeling hides, the barrage of high energy weapons staggered the leaders of the plague hosts. Many fell in the first instants of their arrival with their momentum crippled, and only an unnatural and disgusting resilience prevented total annihilation. However, the rising flood waters increasingly bogged the entire battlefield, and the surviving chaos warriors were far too slow to save their facility. Remaining Aeldari forces swiftly withdrew from the increasingly toxic waters of the site, victorious.

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-battle-report-reclaiming-book-of-st-lucius', s.id, 'Reclaiming the Book of St Lucius', $md$# Battle Report: Reclaiming of the Book of St Lucius

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-reclaiming-book-of-st-lucius/image-1.jpg)

The following narrative battle report covers a game between Carson's Sisters of the Argent Shroud and Paul's Inexorable Death Guard.  Written by Carson Owens.

A world rotting. People crying out in pain, tortured by disease. Katherina looked around desperately for her sisters only to  be met with creatures bearing only a slight resemblance to them. Their flesh twisted with boils. It melted and reformed with every hit of her bolter fire. Behind them, glowing golden, was the Book Of Saint Lucius.

Canoness Kathrina Anais sat bolt upright. Dreams of her homeworld, Kaenore XI, had plagued her since the forgeworld fell to Nugle seven years prior. She knew now what had to be done, The Emperor's true message was finally revealed to her, she had to retake her home and the relic for the glory of the Imperium.

Silent prayers and bolter fire covered the surface of Kaenore XI. Other factions would be screaming as their sisters morphed into demons, but the Order Of The Argent Shroud knew better; Bolter fire was louder than words could ever hope to be.

  

Katherina felt like a coward avoiding battle, but the relic had to be reclaimed. That was her real mission. 

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-reclaiming-book-of-st-lucius/image-2.jpg)

She watched pleased as her sisters took out hoard after hoard of demons on the world she lost so long ago. A smile crept onto her lips as Asa Arzt, her unit's Hospitaller, sang hymns to the God Emperor from the balcony of the convent they grew up in. The same they’d been forced to flee from as Nurgle's sickness took the planet. 

  

Few had been lost, Katherina was skeptical that it had been so easy, but she wasn't one to second guess the God Emperor's mercy. One squad of sisters released from duty and a broken but fixable immolator was a small price to pay for the book of Saint Lucius. 

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-reclaiming-book-of-st-lucius/image-3.jpg)

Katherina's boots clicked on the marble tile of the Hospitaller's ward in their starship base. The ward was unusually quiet. Aza was tending the bodies of the martyrs. She washed their faces and stitched their wounds, ensuring perfection as they were released from duty for one final time. 

  

“This is for you, Asa,” Katherina placed the relic on the desk cluttered with bandages and medical texts, “A gift from the God Emperor for your service.” 

  

The two girls smiled at each other, neither knowing the other was marked for greatness, but still somehow, knowing that their destinies were intertwined nonetheless. 

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-battle-report-entrapment', s.id, 'Entrapment', $md$# Battle Report: The Reckoning

The following narrative battle report covers a game between Bill's Dark Angels and Paul's Inexorable Death Guard.  Written by Bill Foster.

Brother Librarian Marbius rolled his shoulders in his Blue Terminator Plate, it’s deep Navy Blue made him standout significantly from the deep forest green armor plate of his fellow Dark Angels, and the Night Black Armor of the newly arrived Ravenwing Attack Bike Squad on his left flank.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-entrapment/image-1.jpg)

All Space Marine Librarians of all Chapters typically wore the Blue plate signifying their membership in the Libraricus, but Brother Librarian Marbius’s Terminator plate has one outstanding outlier…the Bone White shoulder Pauldron signifying his membership to the Dark Angels Inner Circle, the Deathwing. He grimaced, the campaign has been difficult, with battles lost to the savage Orks, and a closely lost confrontation with the Death Guard, indeed his trusted Lieutenant, Brother Freed still laid in the Apothecarium aboard the Cruiser “Caliban’s Storm”.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-entrapment/image-2.jpg)

The Intercessor Sergeant to his right scanned the noxious fog rolling over the forested hillsides to their front, racked a round into the chamber of his Bolt Rifle, and quietly stated, “The Hated 14th Legion again marches on our lines My Lord”

Marbius replied “Let them know who they march upon Brother…”

The Intercessor Sergeant, started to slowly beat his fist on his chest plate, timing his percussions with his two hearts

Then the Primarus Marines in his squad followed suit, slowly beating their chest plates…and Dark Angels down the line followed suit…The Eradicators in their Heavy Gravis Armor, The Ravenwing astride their attack bikes, even Honored Brother Lucerian enthroned in his Massive Redemptor Dreadnought suit slammed his Combat Fist against his chest plate.

The thunderous percussions echoed over the valley, the valley soon to be filled with Smoke, Gunfire, Shell Casings, Blood, and the bodies of the fallen.

The Dark Angels, started to whisper over the beating of their armor plate “we have come…we are death”

The whisper became a chant “We Have Come…We Are Death”

The chant became a shout “ We Have Come…We are Death!”

The shout became a Battle Cry “WE HAVE COME…WE ARE DEATH!!!”

As the first lines of the Death Guard emerged from the Noxious Fog, Brother Librarian Marbius aimed “Foe Smiter”, his relic Storm Bolter at the enemy and invoked the courage of the Dark Angels “FOR THE LION!!!” and the Dark Angels unleashed their fury and anger.

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-bills-dark-angels', s.id, 'Bill''s Dark Angels', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-mikes-death-guard', s.id, 'Mike''s Death Guard', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-colbys-orks', s.id, 'Colby''s Orks', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-phase-one', s.id, 'Season II — Phase One', $md$# Phase One

With 12 games played in just over one month; phase one of our season two campaign is complete!  Phase one of the campaign saw the Attackers faction run away with 31 Warzone points followed by the Defenders with 23 and the Raiders with 14.  Thanks to everyone for playing and making a ton of hobby progress.  Based on the [Campaign Master Edicts](/archive/recaps/s2-campaign-master-edicts) a few factions will now receive additional requisition points under the Reinforce the Beleaguered rule:

·        Defenders: Brian Foster, Bill Foster, Kris Snyder, and Carson Owens will all receive one free requisition point.

·        Raiders: Colby Joyner, Chris Rice, and Pat Morton will all receive two free requisition points.

Remember that requisition points cannot be stored past five so make sure to spend them if it would take you over five victory points.  I recommend that you increase your supply limits (particularly aim for 75 PL of supply limit in phase two).

Many players only had the opportunity to play a few games and may have ended up losing all of their games.  In this case those players receive 2D6 free experience to distribute across their force due to the campaign edict – The greatest teacher is failure; those players were:

1.      Bill Foster (Dark Angels)

2.      Kris Snyder (Imperial Guard)

3.      Pat Morton (Tyranids)

4.      Chris Rice (Eldar)

I know what you are thinking – man the factions that lost got a ton of buffs; free requisition points, experience points and the like . . . what the hell did the Attackers get for winning?  Players on the winning faction receive five experience points (Grand Alliance) to distribute across their forces.

1.      Mike Holstein (Death Guard)

2.      Justin Nolan (Adeptus Mechanicus)

3.      William Baucom (Space Marines)

4.      Paul Street (Death Guard)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-1.jpg)

## Attackers: 31

Battle Points: 27

Secret Agenda Points: 4

Warseer Predictions Points: 0

Legendary Mission Points: 0

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-2.jpg)

## Defenders: 23

Battle Points: 21

Secret Agenda Points: 2

Warseer Predictions Points: 0

Legendary Mission Points: 0

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-3.jpg)

## Raiders: 14

Battle Points: 14

Secret Agenda Points: 0

Warseer Predictions Points: 0

Legendary Mission Points: 0

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-4.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-5.jpg)

# [Phase One Analysis](/archive/recaps/s2-phase-one-analysis)

A breakdown of the games played, trends, and anticipated changes for phase two.

# [The Reclamation of the Book of Saint Lucius](/archive/recaps/s2-battle-report-reclaiming-book-of-st-lucius)

Check out a narrative battle report of the Defender's faction first win!

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-6.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-7.jpg)

### [Dark Angels](/archive/recaps/s2-bills-dark-angels)

Keep Calm and Hunt the Fallen (Bill Foster)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-8.jpg)

### [Deathwatch](https://docs.google.com/spreadsheets/d/1LIDIrRsdi-vvcPf6OgpvukLde532iHU4xaxDu-V3dOE/edit?usp=sharing)

Burn the Alien! (Brian Foster)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-9.jpg)

[Voyager Marines](https://docs.google.com/spreadsheets/d/1MTMe005KGT0edpTXptf86Q0Ko0g6rCnkNqaZRdRcvNo/edit?usp=sharing) - Renegades

(William Baucom)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-10.jpg)

[Adeptus Mechanicus](https://docs.google.com/spreadsheets/d/19HGo6rhTwAaQaCp4ssbYMRqk6cFivzdPON1Q7nybViQ/edit?usp=sharing) - Scavengers

(Justin Nolan)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-11.jpg)

[Tyranids](https://docs.google.com/spreadsheets/d/1gdkFpKQc9y6Q9oRb6JfbKX8NnTcxT8RhHuvaJlPDhbA/edit?usp=sharing) - Hive Fleet Cerberus

(Pat Morton)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-12.jpg)

[Il-Kaithe Eldar](https://docs.google.com/spreadsheets/d/1XVBaRZUsa3e8wBDlUTOkc_Xfm0hOECUtSJTGFVCb0I4/edit?usp=sharing) - The Perfidious Alien

(Chris Rice)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-13.jpg)

## [Orks! Orks! Orks!](/archive/recaps/s2-colbys-orks)

Colby Joyner's Ork army!

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-14.jpg)

## [Mortarion's Anvil Death Guard](https://docs.google.com/spreadsheets/d/1GOta5hG0BNaFiiwMC3Gp6UEpcttDk3ESQzHY2ISPZLI/edit?usp=sharing)

Mike Holstein's Death Guard!

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-15.jpg)

## [Sisters of the Argent Shroud](https://docs.google.com/spreadsheets/d/1A87_2j_yHHmdc0tDXi7GeCgM9WgYx6k0ub1NQJ0ULPI/edit?usp=sharing)

Carson's Owens faithful Sister's list!

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-16.jpg)

## [Inexorable Death Guard](https://docs.google.com/spreadsheets/d/1xq__sDOTcJA5JysNXDKjaQF3TIny-Eh5Zy-N8rr8FS4/edit?usp=sharing)

Paul Street's Death Guard 2nd Plague Company.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one/image-17.jpg)

## [Valhallan!](https://docs.google.com/spreadsheets/d/1oZiCMWPHdrAPO6JOM6hTG37QvR3BYjnhXnCMqQBMnck/edit?usp=sharing)

I said infantry, lots of infantry.  By Kris Snyder.

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-phase-two', s.id, 'Season II — Phase Two', $md$# Phase Two

Phase two would prove to be our shortest and least participated phase of the campaign - although we did conduct two game days - one at Mighty Meeple and one at Carolina Tabletop Games the overall volume of games was down 33% from the prior phase.  This meant that each game was critically important and the Raiders absolutely killed it this phase going a combined 5-0.  Phase two of the campaign saw the Raiders faction run away with 28 Warzone points followed by the Defenders with 12 and the Attackers with 10.  Highlights from this phase included:

-   A new player!  Tim Schaeffer who got in two games.
    
-   Bill once again painting all of his Dark Angel models.
    
-   Every faction won at least one game.
    

Based on the [Campaign Master Edicts](/archive/recaps/s2-campaign-master-edicts) a few factions will now receive additional requisition points under the Reinforce the Beleaguered rule:

·        Defenders: Brian Foster, Bill Foster, Kris Snyder, and Carson Owens will all receive one free requisition point.

·        Raiders: William Baucom, Mike Holstein, Paul Street, and Justin Nolan will all receive two free requisition points.

Remember that requisition points cannot be stored past five so make sure to spend them if it would take you over five victory points.  I recommend that you increase your supply limits.

Many players only had the opportunity to play a few games and may have ended up losing all of their games.  In this case those players receive 2D6 free experience to distribute across their force due to the campaign edict – The greatest teacher is failure; those players were:

1.      Paul Street (Death Guard) - whew that ugly 0-3!

2.      Kris Snyder (Imperial Guard) - some day the codex will be good!

  

I know what you are thinking – man the factions that lost got a ton of buffs; free requisition points, experience points and the like . . . what the hell did the Attackers get for winning?  Players on the winning faction receive five experience points (Grand Alliance) to distribute across their forces.

1.      Chris Rice (Eldar)

2.      Pat Morton (Tyranids)

3.      Colby Joyner (Orks)

# Table of Contents

[Table of Contents](#h.giftggndzep6)

[Phase Two Warzone Scoring](#h.rkm282qvidg3)

[Attackers: 10](#h.gdc96l6r4rak)

[Defenders: 12](#h.hn092bwh8oiw)

[Raiders: 28](#h.glsqigngh9dm)

[Battle Results](#h.1s34w75x1apx)

[Availability Tracker](#h.uoyumbr2fymz)

[Battle Report: The Reckoning](#h.cp3tyfdjfusi)

[Battle Report: Flood Tide on the Fathom:](#h.4ac8vj7ps7pb)

[Army Lists](#h.wzkilmwaezts)

[Attackers' Army Lists](#h.11ktjsur2pyq)

[Defenders' Army Lists](#h.ui6h3fju2v82)

[Raiders' Army Lists](#h.5dg4omecwbvp)

# Phase Two Warzone Scoring

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-1.jpg)

## Attackers: 10

Battle Points: 9

Secret Agenda Points: 0

Warseer Predictions Points: 0

Legendary Mission Points: 1

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-2.jpg)

## Defenders: 12

Battle Points: 12

Secret Agenda Points: 0

Warseer Predictions Points: 0

Legendary Mission Points: 0

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-3.jpg)

## Raiders: 28

Battle Points: 19

Secret Agenda Points: 4

Warseer Predictions Points: 4

Legendary Mission Points: 1

# Battle Results

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-4.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-5.jpg)

# [Availability Tracker](https://xoyondo.com/dp/RXgwzs10i88Ab65)

Need to schedule games with players?  Check out the availability tracker for phase 2 [here](https://xoyondo.com/dp/RXgwzs10i88Ab65).

# [Battle Report: The Reckoning](/archive/recaps/s2-battle-report-entrapment)

Dark Angels fight the Death Guard in the latest battle report by Bill Foster!

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-6.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-7.jpg)

# [Battle Report: Flood Tide on the Fathom](/archive/recaps/s2-battle-report-flood-tide-on-fathom): 

Check out a new narrative battle report - this time Flood Tide on Fathom about a match between Chris Rice's Eldar and Mike's Death Guard.

# Army Lists

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-8.jpg)

## Attackers' Army Lists

-   [Voyager Marines](https://docs.google.com/spreadsheets/d/1MTMe005KGT0edpTXptf86Q0Ko0g6rCnkNqaZRdRcvNo/edit?usp=sharing) - William Baucom
    
-   [Sanguine Mist Adeptus Mechanicus](https://docs.google.com/spreadsheets/d/19HGo6rhTwAaQaCp4ssbYMRqk6cFivzdPON1Q7nybViQ/edit?usp=sharing) - Justin Nolan
    
-   [Inexorable Death Guard](https://docs.google.com/spreadsheets/d/1xq__sDOTcJA5JysNXDKjaQF3TIny-Eh5Zy-N8rr8FS4/edit?usp=sharing) - Paul Street
    
-   [Mortarion's Anvil Death Guard](https://docs.google.com/spreadsheets/d/1GOta5hG0BNaFiiwMC3Gp6UEpcttDk3ESQzHY2ISPZLI/edit?usp=sharing) - Mike Holstein
    

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-9.jpg)

## Defenders' Army Lists

-   Space Wolves - Tim Schaefer
    
-   [Dark Angels](https://www.carolinafirstandonly.com/bills-dark-angels) - Bill Foster
    
-   [Deathwatch](https://docs.google.com/spreadsheets/d/1LIDIrRsdi-vvcPf6OgpvukLde532iHU4xaxDu-V3dOE/edit?usp=sharing) - Brian Foster
    
-   [Argent Shroud Sisters of Battle](https://docs.google.com/spreadsheets/d/1A87_2j_yHHmdc0tDXi7GeCgM9WgYx6k0ub1NQJ0ULPI/edit?usp=sharing) - Carson Owens
    
-   [Valhallan Imperial Guard](https://docs.google.com/spreadsheets/d/1oZiCMWPHdrAPO6JOM6hTG37QvR3BYjnhXnCMqQBMnck/edit?usp=sharing) - Kris Snyder
    

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-two/image-10.jpg)

## Raiders' Army Lists

-   [Hive Fleet Cerberus Tyranids](https://docs.google.com/spreadsheets/d/1gdkFpKQc9y6Q9oRb6JfbKX8NnTcxT8RhHuvaJlPDhbA/edit?usp=sharing) - Pat Morton
    
-   [Il-Kaithe Eldar](https://docs.google.com/spreadsheets/d/1XVBaRZUsa3e8wBDlUTOkc_Xfm0hOECUtSJTGFVCb0I4/edit?usp=sharing) - Chris Rice
    
-   [Goffz and Evil Sunz Orks](https://www.carolinafirstandonly.com/colbys-orks) - Colby Joyner
    

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-phase-three', s.id, 'Season II — Phase Three', $md$# Phase Three

# Table of Contents

[Table of Contents](#h.hl3cd1heut5s)

[Phase Three Warzone Scoring](#h.kw99fat1iidm)

[Attackers: 29](#h.9bbmnb5hqqrs)

[Defenders: 7](#h.ldv82l1le2oq)

[Raiders: 20](#h.iv5e9hqitsww)

[Battle Results](#h.n4my9pbyufag)

[Availability Tracker](#h.snrbkte7i9nd)

[Army Lists](#h.w4hcd1qyw8gk)

[Attackers' Army Lists](#h.d5lkz61c5e34)

[Defenders' Army Lists](#h.12cw90w7s0kw)

[Raiders' Army Lists](#h.9ap8i9hdsymt)

# Phase Three Warzone Scoring

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-1.jpg)

## Attackers: 29

Battle Points: 26

Secret Agenda Points: 2

Warseer Predictions Points: 0

Legendary Mission Points: 1

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-2.jpg)

## Defenders: 7

Battle Points:7

Secret Agenda Points: 0

Warseer Predictions Points: 0

Legendary Mission Points: 0

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-3.jpg)

## Raiders: 20

Battle Points: 17

Secret Agenda Points: 2

Warseer Predictions Points: 0

Legendary Mission Points: 1

# Battle Results

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-4.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-5.jpg)

# [Availability Tracker](https://xoyondo.com/dp/c7BhMyBz4iW9EUD)

Need to schedule games with players?  Check out the availability tracker for phase 3 [here](https://xoyondo.com/dp/c7BhMyBz4iW9EUD).

# Army Lists

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-6.jpg)

## Attackers' Army Lists

-   [Voyager Marines](https://docs.google.com/spreadsheets/d/1MTMe005KGT0edpTXptf86Q0Ko0g6rCnkNqaZRdRcvNo/edit?usp=sharing) - William Baucom
    
-   [Sanguine Mist Adeptus Mechanicus](https://docs.google.com/spreadsheets/d/19HGo6rhTwAaQaCp4ssbYMRqk6cFivzdPON1Q7nybViQ/edit?usp=sharing) - Justin Nolan
    
-   [Inexorable Death Guard](https://docs.google.com/spreadsheets/d/1xq__sDOTcJA5JysNXDKjaQF3TIny-Eh5Zy-N8rr8FS4/edit?usp=sharing) - Paul Street
    
-   [Mortarion's Anvil Death Guard](https://docs.google.com/spreadsheets/d/1GOta5hG0BNaFiiwMC3Gp6UEpcttDk3ESQzHY2ISPZLI/edit?usp=sharing) - Mike Holstein
    

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-7.jpg)

## Defenders' Army Lists

-   Space Wolves - Tim Schaefer
    
-   [Dark Angels](https://www.carolinafirstandonly.com/bills-dark-angels) - Bill Foster
    
-   [Deathwatch](https://docs.google.com/spreadsheets/d/1LIDIrRsdi-vvcPf6OgpvukLde532iHU4xaxDu-V3dOE/edit?usp=sharing) - Brian Foster
    
-   [Argent Shroud Sisters of Battle](https://docs.google.com/spreadsheets/d/1A87_2j_yHHmdc0tDXi7GeCgM9WgYx6k0ub1NQJ0ULPI/edit?usp=sharing) - Carson Owens
    
-   [Valhallan Imperial Guard](https://docs.google.com/spreadsheets/d/1oZiCMWPHdrAPO6JOM6hTG37QvR3BYjnhXnCMqQBMnck/edit?usp=sharing) - Kris Snyder
    

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-three/image-8.jpg)

## Raiders' Army Lists

-   [Hive Fleet Cerberus Tyranids](https://docs.google.com/spreadsheets/d/1gdkFpKQc9y6Q9oRb6JfbKX8NnTcxT8RhHuvaJlPDhbA/edit?usp=sharing) - Pat Morton
    
-   [Il-Kaithe Eldar](https://docs.google.com/spreadsheets/d/1XVBaRZUsa3e8wBDlUTOkc_Xfm0hOECUtSJTGFVCb0I4/edit?usp=sharing) - Chris Rice
    
-   [Goffz and Evil Sunz Orks](https://www.carolinafirstandonly.com/colbys-orks) - Colby Joyner
    

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-phase-one-analysis', s.id, 'Season II — Phase One Analysis', $md$# Phase One Analysis

With phase one down we thought it would be great to show a rudimentary analysis and summary of the outcomes and potential design changes for Phase Two. \- Paul Street

# Game Sizes

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-1.jpg)

In Phase One almost all games were played at the Incursion level – I found this interesting as I thought there would be more games played at the Combat Patrol level; this clearly shows that players in our group prefer larger to smaller games and the current adage that 50 PL games are the sweet spot between army building, gameplay decisions, and play time seems to hold true.  I suspect that we will find half our games in Phase 2 will be Strike Force size – although I hold out hope we will see some Combat Patrol level games also (but I am a sucker for the fast paced games of Combat Patrol).

# Win Rates

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-2.jpg)

Win rates in the campaign were a little lopsided in phase one – the Attackers almost won half of all games – and in the phase we had four players go undefeated:

1.      Mike Holstein (Death Guard) 2-0

2.      Justin Nolan (Adeptus Mechanicus) 2-0

3.      Carson Ownes (Sisters of Battle) 2-0

4.      Colby Joyner (Orks) 3-0

Of these players two had very close games (Mike’s Death Guard beat Bill’s Dark Angels in a game that went down to the wire – and Carson’s Sisters won a game against my Death Guard which was literally the closest game of Warhammer I have ever played).  What is more interesting is that no army with an 8th edition codex won a game . . .

1.      Pat Morton (Tyranids) 0-1

2.      Chris Rice (Eldar) 0-1

3.      Kris Snyder (Imperial Guard) 0-3

This leads me to consider that next season 8th edition books may need some kind of buff.  Potentially something like all Warlord and Relic traits do not cost requisition points, or they gain additional command points based on game size (2 for combat patrol, 3 for incursion, 4 for strike force . . . etc.).  We’ll see if, as players get more games with their armies, the wins will become more evenly distributed.

# Warseers and Portents

One of my favorite created Campaign Edicts was Warseers and Portents.  The name is a reference to an old Warhammer website from the early 2000s (Portent) that had amazing rumors and was very well run.  When Portent finally shut down it was replaced by Warseer – which at first was great then turned into utter garbage (the dark days of 5th thru 7th edition 40k and 8th edition fantasy).  Anyways I thought it was cool to have a mechanic that would engage players in other games by having them predict the winners/losers and battle size.

# Warseers and Portents - Phase One Results

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-3.jpg)

So the participation rate for Phase One was only at 50% - I think this was due to half the players not playing around with the website much – having said that – this was an optional task players and players were not required to make a prediction.

Additionally in phase one we asked for the player to predict the battle size – in all cases every player picked Incursion.  This lead me to drop the battle size from the prediction requirement – generally whenever you see a system where everyone picks the same thing . . . you don’t really have an option there and you should remove it.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-4.jpg)

When it came to choosing winners people focused on Chris’s Eldar, my Death Guard (Paul), and Colby’s Orks for wins.  Pink is my army (Paul) and green was William Baucom’s Space Marines.  One of the predictions for Colby’s Orks winning is for phase two.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-5.jpg)

When it came to predicting the loser – almost half the predictions were me . . . really?  Dark red is Chris Rice’s Eldar – with the exception of me it seems loser predictions were spread out.  I tend to think that the lot of you were griefing me.

Finally we get to the meat; did anyone pick a winner in phase one?  The answer was surprisingly . . . no.  Here were the predictions (predictor omited to protect the innocent):

1.      Death Guard (PS) over Sisters (CO) – this battle happened twice but Sister’s won both times.

2.      Space Marines (WB) over Eldar (CR) – this battle did not occur.

3.      Eldar (CR) over Deathwatch (BF) – this battle did not occur.

4.      Orks (CJ) over Death Guard (PS) – this battle did not occur.

5.      Eldar (CR) over Death Guard (PS) – this battle did not occur.

6.      Death Guard (PS) over Dark Angels (BF) – this battle did not occur.

I was a little surprised in that we had 6 predictions and only one battle occurred . . . that got me to thinking . . . how many winner/loser combinations were possible?  Based on 11 players and two player games – the answer was actually 110 ([math](https://www.hackmath.net/en/calculator/combinations-and-permutations?n=11&k=2&order=1&repeat=0)).

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-phase-one-analysis/image-6.jpg)

This means if you randomly picked the winner and loser your chances of picking correctly was very low (<1%).  Now of course players can also limit their picks with better information – they can pick people who live near each other and are likely to play . . . but even if you pick a combo from the smallest hub (Greensboro) there are still [20 combinations](https://www.hackmath.net/en/calculator/combinations-and-permutations?n=5&k=2&order=1&repeat=0).  That means even with good information the chance of succeeding is still around 5%.  In light of low chance of success we’ll increase the reward for Portents and Warseers to 4 Warzone points in phase two – this would make it equivalent to winning an incursion level game – which I think is reasonable for making a 1/20 chance prediction.

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

insert into public.recaps (slug, season_id, title, body_md, published_at)
select 's2-campaign-master-edicts', s.id, 'Season II — Campaign Master Edicts', $md$# Campaign Master Edicts

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-1.jpg)

# Reinforce the Beleaguered

At the end of each campaign phase, each player can be awarded additional Requisition points based on how their alliance did during the phase. The alliance that earned the fewest war zone points is awarded the most Requisition points, representing that alliance calling for aid and doubling their efforts to achieve victory in the following campaign phase. Remember that each player can never have more than 5 Requisition points; any excess points are lost.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-2.jpg)

# The greatest teacher is failure

At the end of a campaign phase, if a player lost all the games they played during that phase, they can roll 2D6. They gain that many experience points to distribute freely across the units in their Crusade force.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-3.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-4.jpg)

# A Grand Alliance

At the end of each campaign phase, each player from the winning alliance gains 5 experience points to distribute freely across units in their Crusade force.

# Dark Vengeance

If a player defeats an enemy player who defeated them in their previous meeting in the campaign, after that game, the winning player can select one additional unit from their army to be Marked for Greatness.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-5.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-6.jpg)

# Keep it Secret - Keep it Safe!

At the beginning of each Campaign Phase - players will roll on the [Secret Order](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-charadon/#Secret-Orders) list.  If they achieve their Secret Order they will earn 2 war zone points for their faction.

# Warseers and Portents

At the beginning of each Campaign Phase - each player will submit a prediction: they must choose two players and the outcome of the battle (i.e. (Space Marines) William Baucom and (Space Marines) Brian Foster will play and William Baucom will Win).  If by the end of the campaign phase this condition is met, the predictor will score 4\* war zone points for their faction.

\*This value was increased from 2 to 4 after phase one.  Also the requirement to pick battle size was dropped.

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-7.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/recaps/s2-campaign-master-edicts/image-8.jpg)

# The Legend Killer

Once per campaign phase players may play that phases legendary mission for an additional War Zone point (phase one - [Rout on Okharium](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-charadon/#Rout-on-Okharium); phase two - [Flood Tide on Fathom](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-charadon/#Flood-Tide-on-Fathom); phase three - [Desperation and Despair](https://wahapedia.ru/wh40k9ed/the-rules/war-zone-charadon/#Desperation-and-Despair)).

  2024.$md$, now()
from public.seasons s where s.slug = 'season-2'
on conflict (slug) do nothing;

-- ----------------------------------------------------------------------------
-- Archive pages (S2 reference)
-- ----------------------------------------------------------------------------

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-player-hub-charlotte', 'Season II — Player Hub: Charlotte', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, 's2-reference', 2)
on conflict (slug) do nothing;

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-player-hub-greensboro', 'Season II — Player Hub: Greensboro', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, 's2-reference', 3)
on conflict (slug) do nothing;

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-player-faction-attacker', 'Season II — Player Faction: Attacker', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, 's2-reference', 4)
on conflict (slug) do nothing;

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-player-faction-defender', 'Season II — Player Faction: Defender', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, 's2-reference', 5)
on conflict (slug) do nothing;

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-player-faction-raider', 'Season II — Player Faction: Raider', $md$_This page existed as a placeholder on the original Google Sites and has not yet been written up._$md$, 's2-reference', 6)
on conflict (slug) do nothing;

insert into public.archive_pages (slug, title, body_md, category, display_order)
values ('s2-house-rules', 'Season II — House Rules', $md$# House Rules

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-1.jpg)

# Down to the Wire

Add the following text to each Narrative Mission in the Mission Objectives section for all Progressive Objectives that are scored at the end of the Command Phase.  In the fifth battle round, the player who has the second turn does not score victory points for this objective at the end of their Command phase; instead, at they score the end of their turn.

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-2.jpg)

# Dice for the Dice Gods

When units are choosing battle honors that have a roll-able table such as [Battle Traits](https://wahapedia.ru/wh40k9ed/the-rules/narrative-play/#Battle-Traits), [Weapon Enhancements](https://wahapedia.ru/wh40k9ed/the-rules/narrative-play/#Weapon-Enhancements), or [Battle Scars](https://wahapedia.ru/wh40k9ed/the-rules/narrative-play/#Battle-Scars) - the player must roll on the table, they are not permitted to choose their upgrades unless the mission rules state specifically that they choose a battle trait of their choice.  Players may select Warlord Traits, Relics, and Crusade Relics as normal.

# Architect of Fate

To balance out the Dice for the Dice Gods rule when it provides a trait that has no utility, the following Requisition is added to the [base rulebook requisitions](https://wahapedia.ru/wh40k9ed/the-rules/narrative-play/#Requisitions).

ARCHITECT OF FATE - 1 RP

Purchase this Requisition immediately after you have rolled an upgrade for a unit that has gained a promotion (ranked up) OR immediately when a unit has gained a battle scar.  You may re-roll the die roll when adding your battle honor or determining your battle scar.  If your Order of battle contains any units with the keyword TZEENTCH or AELDARI PSYKER roll a d6 when you purchase this requisition, on a roll of 3+ this requisition costs 0 instead of 1.  This requisition can only be used once per upgrade or battle scar (i.e. you may not re-roll multiple times in a row).

\*Because this requisition was not selected in phase one, the cost has been reduced and a mechanic introduced which can make it free for TZEENTCH or AELDARI armies.

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-3.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-4.jpg)

# Hidden Cost of Daemon Worship

When using the [Daemon Ritual](https://wahapedia.ru/wh40k9ed/factions/chaos-daemons/#Daemonic-Ritual) ability, controlling players must spend one Command Point per die used in the summoning ability.  I.E. if a player wishes to summon a unit of Daemons with two dice, they would pay two command points in order to attempt the summoning roll - if the summoning roll fails they still lose the spent Command Points.

# The Bell of Lost Souls

During Phase Three of the Campaign if an Imperial Player's faction is in last place (i.e. has the lowest Strategic Value of all factions) this rule will go into effect.  

Instead of moving in their Movement phase, any IMPERIUM CHARACTER can, at the end of their Movement phase, attempt to summon a [DAMNED LEGIONNAIRE](https://wahapedia.ru/wh40k9ed/factions/space-marines/Damned-Legionnaires) unit with this ability by performing an Imperial Prayer (the character cannot do so if they arrived as reinforcements this turn, or if they were themselves summoned to the battlefield this turn).

Roll up to 3 dice – this is your summoning roll. For each die you roll you must spend a command point.  You can summon one new [DAMNED LEGIONNAIRE](https://wahapedia.ru/wh40k9ed/factions/space-marines/Damned-Legionnaires) unit with the Imperial Prayer ability to the battlefield that has a Power Rating equal to or less than the total result.  This unit is treated as reinforcements for your army and can be placed anywhere on the battlefield that is wholly within 12" of the character and more than 9" from any enemy model. If the total rolled is insufficient to summon any unit, the prayer fails and no new unit is summoned.

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-5.jpg)

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-6.jpg)

# For Every Sin a Painted Miniature

Summoned units such as Daemons summoned via [Daemonic Ritual](https://wahapedia.ru/wh40k9ed/factions/chaos-daemons/#Daemonic-Ritual) or [Damned Legionnaires](https://wahapedia.ru/wh40k9ed/factions/space-marines/Damned-Legionnaires) summoned by an Imperial Prayer must be painted.  The painting gods declare their due for free units.

# A Space Marine is Never Late, Nor Is He Early

Strategic Reserve and Reinforcement units can never arrive on the battlefield in the first battle round. Any Strategic Reserve or Reinforcement unit that has not arrived on the battlefield by the end of the third battle round counts as having been destroyed, as do any units embarked within them (this does not apply to units that are placed into Strategic Reserves after the first battle round has started).

![](https://ik.imagekit.io/carolinafirstandonly/pages/s2-house-rules/image-7.jpg)

  2024.$md$, 's2-reference', 1)
on conflict (slug) do nothing;
