/**
 * Generate packages/database/supabase/migrations/0006_seed_archive_content.sql
 * from the takeout extractor's output + the hand-curated Showdown markdown.
 *
 * Usage:
 *   pnpm --filter @cfo/migrate-google-site exec tsx src/build-migration.ts \
 *     --in       out/takeout.json \
 *     --manifest takeout-manifest.json \
 *     --showdown ../../content/events/showdown-at-snyders.md \
 *     --out      ../../packages/database/supabase/migrations/0006_seed_archive_content.sql
 */

import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';

interface ManifestItem {
    page: string;
    slug: string;
    title?: string;
    kind?: 'season' | 'event' | 'recap' | 'page';
    imagekitFolder: string;
}

interface ExtractResult {
    page: string;
    slug: string;
    title: string;
    bodyMd: string;
    heroImageUrl: string | null;
    uploads: Record<string, string>;
    imageCount: number;
}

interface TakeoutOutput {
    results: Record<string, ExtractResult>;
}

function args() {
    const { values } = parseArgs({
        options: {
            in: { type: 'string' },
            manifest: { type: 'string' },
            showdown: { type: 'string' },
            out: { type: 'string' },
        },
    });
    if (!values.in || !values.manifest || !values.showdown || !values.out) {
        throw new Error('--in, --manifest, --showdown, --out are required');
    }
    return values as {
        in: string;
        manifest: string;
        showdown: string;
        out: string;
    };
}

/** Pick a unique $tag$ that doesn't appear inside `body`. */
function dollarQuote(body: string): string {
    for (const tag of ['md', 'md1', 'md2', 'md3', 'md_body', 'md_x']) {
        if (!body.includes(`$${tag}$`)) return tag;
    }
    return `md_${Math.random().toString(36).slice(2, 8)}`;
}

function quote(body: string): string {
    const tag = dollarQuote(body);
    return `$${tag}$${body}$${tag}$`;
}

/** Strip markdown frontmatter (---\n...\n---) if present. */
function stripFrontmatter(md: string): string {
    if (!md.startsWith('---')) return md;
    const end = md.indexOf('\n---', 3);
    return end < 0 ? md : md.slice(end + 4).replace(/^\s+/, '');
}

const SEASON_OVERRIDES: Record<
    string,
    { year: number | null; display_order: number }
> = {
    'season-1': { year: 2021, display_order: 1 },
    'season-2': { year: 2021, display_order: 2 },
    'season-3': { year: 2022, display_order: 3 },
};

const EVENT_MAPPING: Record<
    string,
    { fromSlug: string; eventDate: string | null; displayOrder: number }
> = {
    'showdown-at-snyders': {
        fromSlug: 'special-event-1',
        eventDate: '2023-12-01',
        displayOrder: 1,
    },
    'old-alliances': {
        fromSlug: 'special-event-2',
        eventDate: '2024-07-27',
        displayOrder: 2,
    },
    drafted: {
        fromSlug: 'special-event-3',
        eventDate: '2026-01-01',
        displayOrder: 3,
    },
};

const PAGE_DISPLAY_ORDER: Record<string, number> = {
    's2-house-rules': 1,
    's2-player-hub-charlotte': 2,
    's2-player-hub-greensboro': 3,
    's2-player-faction-attacker': 4,
    's2-player-faction-defender': 5,
    's2-player-faction-raider': 6,
};

const PLACEHOLDER_BODY =
    '_This page existed as a placeholder on the original Google Sites and has not yet been written up._';

async function main() {
    const { in: inPath, manifest: manifestPath, showdown, out } = args();
    const data: TakeoutOutput = JSON.parse(await readFile(inPath, 'utf8'));
    const manifest: { items: ManifestItem[] } = JSON.parse(
        await readFile(manifestPath, 'utf8'),
    );
    const showdownMd = stripFrontmatter(await readFile(showdown, 'utf8'));

    const byKind: Record<'season' | 'event' | 'recap' | 'page', ManifestItem[]> = {
        season: [],
        event: [],
        recap: [],
        page: [],
    };
    for (const it of manifest.items) {
        byKind[it.kind ?? 'recap'].push(it);
    }

    const lines: string[] = [];
    lines.push(
        '-- ============================================================================',
        '-- 0006_seed_archive_content.sql — Phase 1 content migration',
        '--',
        '-- Updates the placeholder shells (0004) with content extracted from the',
        '-- Google Sites takeout. Embedded markdown bodies use dollar-quoted strings;',
        '-- image URLs point at the ImageKit account.',
        '--',
        '-- Generated by tools/migrate-google-site/src/build-migration.ts',
        '-- ============================================================================',
        '',
        '-- ----------------------------------------------------------------------------',
        '-- Seasons',
        '-- ----------------------------------------------------------------------------',
        '',
    );

    // Season 1: minimal, the source page says "no link or images; we just played games!".
    const s1 = SEASON_OVERRIDES['season-1']!;
    lines.push(
        `update public.seasons set`,
        `    name = 'Season I (2021)',`,
        `    year = ${s1.year},`,
        `    display_order = ${s1.display_order},`,
        `    description_md = ${quote(
            'We played the first season of crusade campaigns in early 2021. No public writeup made it onto the old Google Sites — _"we just played games!"_ as the source page put it.',
        )}`,
        `where slug = 'season-1';`,
        '',
    );

    for (const slug of ['season-2', 'season-3']) {
        const r = data.results[slug];
        if (!r) continue;
        const ov = SEASON_OVERRIDES[slug];
        lines.push(
            `update public.seasons set`,
            `    name = ${pgString(r.title)},`,
            `    year = ${ov?.year ?? 'null'},`,
            `    display_order = ${ov?.display_order ?? 0},`,
            `    hero_image_url = ${r.heroImageUrl ? pgString(r.heroImageUrl) : 'null'},`,
            `    description_md = ${quote(r.bodyMd)}`,
            `where slug = '${slug}';`,
            '',
        );
    }

    lines.push(
        '-- ----------------------------------------------------------------------------',
        '-- Special events (rename special-event-N → real slugs)',
        '-- ----------------------------------------------------------------------------',
        '',
    );

    // Showdown uses hand-curated markdown.
    {
        const showdownMapping = EVENT_MAPPING['showdown-at-snyders']!;
        lines.push(
            `update public.archive_events set`,
            `    slug = 'showdown-at-snyders',`,
            `    name = 'Showdown at Snyder''s',`,
            `    event_date = '${showdownMapping.eventDate}',`,
            `    display_order = ${showdownMapping.displayOrder},`,
            `    hero_image_url = 'https://ik.imagekit.io/carolinafirstandonly/events/showdown-at-snyders/round-one-knight-shelling.jpg',`,
            `    description_md = ${quote(showdownMd)}`,
            `where slug = '${showdownMapping.fromSlug}';`,
            '',
        );
    }

    for (const slug of ['old-alliances', 'drafted'] as const) {
        const r = data.results[slug];
        const mapping = EVENT_MAPPING[slug];
        if (!r || !mapping) continue;
        lines.push(
            `update public.archive_events set`,
            `    slug = '${slug}',`,
            `    name = ${pgString(r.title)},`,
            `    event_date = ${mapping.eventDate ? `'${mapping.eventDate}'` : 'null'},`,
            `    display_order = ${mapping.displayOrder},`,
            `    hero_image_url = ${r.heroImageUrl ? pgString(r.heroImageUrl) : 'null'},`,
            `    description_md = ${quote(r.bodyMd)}`,
            `where slug = '${mapping.fromSlug}';`,
            '',
        );
    }

    lines.push(
        '-- ----------------------------------------------------------------------------',
        '-- Recaps (all attached to season-2)',
        '-- ----------------------------------------------------------------------------',
        '',
    );

    for (const it of byKind.recap) {
        const r = data.results[it.slug];
        if (!r) continue;
        const body = r.bodyMd.trim().length > 50 ? r.bodyMd : PLACEHOLDER_BODY;
        lines.push(
            `insert into public.recaps (slug, season_id, title, body_md, published_at)`,
            `select '${it.slug}', s.id, ${pgString(r.title)}, ${quote(body)}, now()`,
            `from public.seasons s where s.slug = 'season-2'`,
            `on conflict (slug) do nothing;`,
            '',
        );
    }

    lines.push(
        '-- ----------------------------------------------------------------------------',
        '-- Archive pages (S2 reference)',
        '-- ----------------------------------------------------------------------------',
        '',
    );

    for (const it of byKind.page) {
        const r = data.results[it.slug];
        if (!r) continue;
        const body = r.bodyMd.trim().length > 50 ? r.bodyMd : PLACEHOLDER_BODY;
        const order = PAGE_DISPLAY_ORDER[it.slug] ?? 0;
        lines.push(
            `insert into public.archive_pages (slug, title, body_md, category, display_order)`,
            `values ('${it.slug}', ${pgString(r.title)}, ${quote(body)}, 's2-reference', ${order})`,
            `on conflict (slug) do nothing;`,
            '',
        );
    }

    await writeFile(resolve(out), lines.join('\n'), 'utf8');
    console.log(`Wrote ${lines.length} SQL lines to ${out}`);
}

function pgString(s: string): string {
    return `'${s.replace(/'/g, "''")}'`;
}

main().catch((err) => {
    console.error(`failed: ${(err as Error).message}`);
    process.exit(1);
});
